---
name: Checks
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wait
        run: sleep 90
      - name: Done
        run: echo "Done"
