# Automatically release to the developer environment when pushed to `main`.
---
name: "Auto-Release: Dev"
on:
  workflow_run:
    workflows:
      - Checks
    types:
      - completed
    branches:
      - main
jobs:
  release:
    uses: ./.github/workflows/release_template.yml
    with:
      name: Dev Environment
    secrets: inherit
