# Release to select environment from select Branch / Tag via the GitHub Actions UI.
---
name: Release (Manual)
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true
        type: string
jobs:
  release:
    uses: ./.github/workflow_templates/release.yml
    with:
      name: ${{ inputs.name }}
    secrets: inherit
