---
name: 🔒 Release (Template)
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
jobs:
  greet:
    name: Greet
    runs-on: ubuntu-latest
    steps:
      - name: Update Deployment Status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: https://localhost:4000/
          state: in_progress
          deployment-id: ${{ inputs.name }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Greet
        run: echo "Hello ${{ inputs.name }}"
      - name: Wait
        run: sleep 30
      - name: Update Deployment Status
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: https://localhost:4000/
          state: success
          deployment-id: ${{ inputs.name }}
      - name: Update Deployment Status
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: https://localhost:4000/
          state: failure
          deployment-id: ${{ inputs.name }}
