# Release to select environment from select Branch / Tag via the GitHub Actions UI.
---
name: Release
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true
        type: string
jobs:
  release:
    uses: ./.github/workflows/release_template.yml
    with:
      name: ${{ inputs.name }}
    secrets: inherit
